This file is just messing around looking at the target variables and trying some calculations.

In [1]:
%%sql
-- looking at 
SELECT *, s/c AS p_insured 
FROM (
    SELECT st, SUM(c) s, COUNT(1) c FROM (
        SELECT st, CASE WHEN hins1+hins2+hins3+hins4+hins5+hins6+hins7 > 0 THEN 1 ELSE 0 END c FROM test.silver.data.census
    ) GROUP BY st
) ORDER BY p_insured DESC

23/12/04 02:49:54 WARN SparkSession: Using an existing Spark session; only runtime SQL configurations will take effect.

+----+--------+--------+--------------------+
| st |      s |      c |          p_insured |
+----+--------+--------+--------------------+
| 25 | 118366 | 121079 | 0.9775931416678367 |
| 50 |  10996 |  11374 |  0.966766309126077 |
| 44 |  17413 |  18035 | 0.9655115054061547 |
| 15 |  23636 |  24493 | 0.9650104111378761 |
| 27 |  87904 |  91594 | 0.9597135183527306 |
|  9 |  58305 |  60870 | 0.9578610152784623 |
| 19 |  50251 |  52560 | 0.9560692541856926 |
| 33 |  22094 |  23150 | 0.9543844492440605 |
| 36 | 316396 | 331851 | 0.9534278938439239 |
| 26 | 155471 | 163362 | 0.9516962329060614 |
| 38 |  11767 |  12385 | 0.9501009285425919 |
| 10 |  15105 |  15936 | 0.9478539156626506 |
| 42 | 203888 | 215175 | 0.9475450214941327 |
| 55 |  93323 |  98536 | 0.9470954777949175 |
| 24 |  95497 | 100844 | 0.9469775098171433 |
| 72 |  44585 |  47106 | 0.9464824013926039 |
| 21 |  69569 |  73739 | 0.9434491924219206 |
| 53 | 120734 | 127984 | 0.9433522940367546 |
| 41 |  66896 |  70946 | 0.9429143292081301 |
| 23 |  22462 |  23868 | 0.9410926763867941 |
| 39 | 182154 | 193744 | 0.9401787926335783 |
| 51 | 133373 | 141974 |  0.939418485074732 |
| 34 | 141361 | 150581 | 0.9387704956136564 |
| 17 | 191665 | 204349 | 0.9379297182760865 |
| 46 |  13149 |  14027 |   0.93740643045555 |
| 31 |  28906 |  30854 |  0.936863939845725 |
| 30 |  16392 |  17502 | 0.9365786767226603 |
| 35 |  30131 |  32260 | 0.9340049597024178 |
| 18 | 101991 | 109392 | 0.9323442299254059 |
|  6 | 585461 | 628255 | 0.9318843463243428 |
| 54 |  27167 |  29231 | 0.9293900311313332 |
|  8 |  88491 |  95417 | 0.9274133540144838 |
|  2 |   9425 |  10175 | 0.9262899262899262 |
| 49 |  46641 |  50643 | 0.9209762454830875 |
| 16 |  26624 |  28928 | 0.9203539823008849 |
| 22 |  65736 |  71575 | 0.9184212364652462 |
| 20 |  42513 |  46353 | 0.9171574655362112 |
|  4 | 108044 | 118800 | 0.9094612794612794 |
| 29 |  91671 | 101208 | 0.9057683187099834 |
| 45 |  78315 |  86612 | 0.9042049600517249 |
|  5 |  44206 |  48915 | 0.9037309618726362 |
| 37 | 157433 | 174277 | 0.9033492658239469 |
|  1 |  73804 |  82068 | 0.8993030170102841 |
| 47 | 103063 | 114772 | 0.8979803436378211 |
| 32 |  43898 |  49002 | 0.8958409860822008 |
| 56 |   8287 |   9281 | 0.8928994720396509 |
| 12 | 312019 | 352545 | 0.8850472989263782 |
| 40 |  52805 |  60132 | 0.8781514002527773 |
| 28 |  40922 |  46788 | 0.8746259724715739 |
| 13 | 143425 | 165647 |  0.865847253496894 |
| 48 | 362387 | 436765 | 0.8297070507023228 |
+----+--------+--------+--------------------+